# 构建张量

## 导入torchm模块

In [1]:
import torch
import numpy
print(torch.__version__)

1.4.0


## 构造一个随机初始化的矩阵

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[6.7133e-07, 1.0424e-11, 1.0384e-08],
        [1.3444e+22, 8.4936e+20, 1.2794e+22],
        [2.1476e-04, 6.7412e+22, 4.0972e-11],
        [4.2330e+21, 1.6534e+19, 3.0478e+32],
        [1.6255e-43, 0.0000e+00, 0.0000e+00]])


## 构造一个填充零且dtype long的矩阵

In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## 直接从数据构造张量

In [4]:
x = torch.tensor([5.5, 3, 4, 5])
print(x)

tensor([5.5000, 3.0000, 4.0000, 5.0000])


## 构造一个填充一且dtype double的矩阵

In [5]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## 基于现有的张量创建张量

In [6]:
x = torch.randn_like(x, dtype=torch.float64)
print(x)
print(x.size())

tensor([[-0.2695,  1.2353,  2.1627],
        [ 0.7293, -0.5053, -0.0986],
        [ 0.4515,  0.7952,  0.5091],
        [-0.7061, -0.2998, -0.7785],
        [-0.7688,  0.1298, -1.2037]], dtype=torch.float64)
torch.Size([5, 3])


## 张量的加法-I

In [7]:
y = torch.rand(5, 3)
z1 = x + y
print(z1)

tensor([[ 0.0922,  1.7986,  3.0519],
        [ 1.0873, -0.3655,  0.2392],
        [ 0.9178,  1.6973,  1.2786],
        [-0.2723,  0.0511, -0.1409],
        [ 0.1964,  0.3343, -0.7658]], dtype=torch.float64)


## 张量的加法-II

In [8]:
z2 = torch.add(x, y)
print(z2)

tensor([[ 0.0922,  1.7986,  3.0519],
        [ 1.0873, -0.3655,  0.2392],
        [ 0.9178,  1.6973,  1.2786],
        [-0.2723,  0.0511, -0.1409],
        [ 0.1964,  0.3343, -0.7658]], dtype=torch.float64)


## 张量的加法-III

In [9]:
z3 = torch.empty(5, 3)
torch.add(x, y, out=z3)
print(z3)

tensor([[ 0.0922,  1.7986,  3.0519],
        [ 1.0873, -0.3655,  0.2392],
        [ 0.9178,  1.6973,  1.2786],
        [-0.2723,  0.0511, -0.1409],
        [ 0.1964,  0.3343, -0.7658]])


## 张量的加法-IV

In [10]:
y.add_(x)
print(y)

tensor([[ 0.0922,  1.7986,  3.0519],
        [ 1.0873, -0.3655,  0.2392],
        [ 0.9178,  1.6973,  1.2786],
        [-0.2723,  0.0511, -0.1409],
        [ 0.1964,  0.3343, -0.7658]])


## 获取一列

In [11]:
temp = y[:, 1]
print(temp)

tensor([ 1.7986, -0.3655,  1.6973,  0.0511,  0.3343])


## 调整张量的形状

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size())
print(x)
print(y.size())
print(y)
print(z.size())
print(z)

torch.Size([4, 4])
tensor([[ 1.3093,  1.9386, -0.6783, -1.8335],
        [ 0.1263, -0.2076, -0.1838, -0.8468],
        [ 0.9618, -1.0500,  1.0578,  0.7391],
        [-1.3491, -0.5793,  0.5118, -1.1665]])
torch.Size([16])
tensor([ 1.3093,  1.9386, -0.6783, -1.8335,  0.1263, -0.2076, -0.1838, -0.8468,
         0.9618, -1.0500,  1.0578,  0.7391, -1.3491, -0.5793,  0.5118, -1.1665])
torch.Size([2, 8])
tensor([[ 1.3093,  1.9386, -0.6783, -1.8335,  0.1263, -0.2076, -0.1838, -0.8468],
        [ 0.9618, -1.0500,  1.0578,  0.7391, -1.3491, -0.5793,  0.5118, -1.1665]])


## tensor to value

In [13]:
x = torch.randn(1)
print('x:', x)
value = x.item()
print('value:', value)

x: tensor([1.1945])
value: 1.1945050954818726


## tensor to numpy

In [14]:
x = torch.ones(6)
y = x.numpy()
print('x:', x)
print('y:', y)

x: tensor([1., 1., 1., 1., 1., 1.])
y: [1. 1. 1. 1. 1. 1.]


## numpy to tensor

In [15]:
numpyValue = numpy.ones(4)
print('numpyValue:', numpyValue)
tensorVlue = torch.from_numpy(numpyValue)
print('tensorvalue:', tensorVlue)

numpyValue: [1. 1. 1. 1.]
tensorvalue: tensor([1., 1., 1., 1.], dtype=torch.float64)


## 跟踪操作

In [16]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


### 进行张量计算

In [17]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


### 查看计算历史

In [18]:
print(y.grad_fn)

## 再次进行操作

In [19]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>)
tensor(12., grad_fn=<MeanBackward0>)


## 设置跟踪

In [20]:
a = torch.randn(2, 2)
print(a)
a = (a * 3) / (a -1)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor([[ 0.8191,  0.2891],
        [-1.7024, -0.7140]])
tensor([[-13.5844,  -1.2202],
        [  1.8899,   1.2497]])
False
True
tensor(191.1593, grad_fn=<SumBackward0>)


## 停止跟踪-I

In [21]:
a.requires_grad_(False)
print(a.requires_grad)

False


## 反向传播

In [22]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
print(y)

while y.data.norm() < 1000:
    y = y * 2
print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(v)

tensor([ 0.1225, -0.2525, -0.9756], requires_grad=True)
tensor([ 0.2451, -0.5050, -1.9512], grad_fn=<MulBackward0>)
tensor([ 125.4733, -258.5648, -999.0305], grad_fn=<MulBackward0>)
tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])


## 停止跟踪-II

In [23]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False
