# 构建张量

## 导入torchm模块

In [17]:
import torch
import numpy
print(torch.__version__)

1.3.1


## 构造一个随机初始化的矩阵

In [18]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 3.6893e+19, 0.0000e+00],
        [3.6893e+19, 1.1210e-44, -0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


## 构造一个填充零且dtype long的矩阵

In [19]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## 直接从数据构造张量

In [20]:
x = torch.tensor([5.5, 3, 4, 5])
print(x)

tensor([5.5000, 3.0000, 4.0000, 5.0000])


## 构造一个填充一且dtype double的矩阵

In [21]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## 基于现有的张量创建张量

In [22]:
x = torch.randn_like(x, dtype=torch.float64)
print(x)
print(x.size())

tensor([[ 0.1236,  0.4491,  0.3269],
        [-1.2497, -1.0837,  1.7347],
        [ 0.7712, -0.0602,  0.5391],
        [-0.7182, -0.7519, -1.0561],
        [-2.0719,  2.3976,  0.4275]], dtype=torch.float64)
torch.Size([5, 3])


## 张量的加法-I

In [23]:
y = torch.rand(5, 3)
z1 = x + y
print(z1)

tensor([[ 0.4120,  1.0332,  1.0992],
        [-0.4140, -0.7281,  2.6932],
        [ 0.8377,  0.4082,  0.6352],
        [-0.1814, -0.0933, -0.6025],
        [-1.9720,  2.6750,  0.8200]], dtype=torch.float64)


## 张量的加法-II

In [24]:
z2 = torch.add(x, y)
print(z2)

tensor([[ 0.4120,  1.0332,  1.0992],
        [-0.4140, -0.7281,  2.6932],
        [ 0.8377,  0.4082,  0.6352],
        [-0.1814, -0.0933, -0.6025],
        [-1.9720,  2.6750,  0.8200]], dtype=torch.float64)


## 张量的加法-III

In [25]:
z3 = torch.empty(5, 3)
torch.add(x, y, out=z3)
print(z3)

tensor([[ 0.4120,  1.0332,  1.0992],
        [-0.4140, -0.7281,  2.6932],
        [ 0.8377,  0.4082,  0.6352],
        [-0.1814, -0.0933, -0.6025],
        [-1.9720,  2.6750,  0.8200]])


## 张量的加法-IV

In [26]:
y.add_(x)
print(y)

tensor([[ 0.4120,  1.0332,  1.0992],
        [-0.4140, -0.7281,  2.6932],
        [ 0.8377,  0.4082,  0.6352],
        [-0.1814, -0.0933, -0.6025],
        [-1.9720,  2.6750,  0.8200]])


## 获取一列

In [27]:
temp = y[:, 1]
print(temp)

tensor([ 1.0332, -0.7281,  0.4082, -0.0933,  2.6750])


## 调整张量的形状

In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size())
print(x)
print(y.size())
print(y)
print(z.size())
print(z)

torch.Size([4, 4])
tensor([[-1.5137, -0.0535,  1.8024,  0.3257],
        [ 1.2464,  0.2828, -1.1639, -0.2219],
        [-1.1041, -1.8165,  2.2474, -0.7293],
        [-0.6931, -0.9882,  2.3314,  2.1616]])
torch.Size([16])
tensor([-1.5137, -0.0535,  1.8024,  0.3257,  1.2464,  0.2828, -1.1639, -0.2219,
        -1.1041, -1.8165,  2.2474, -0.7293, -0.6931, -0.9882,  2.3314,  2.1616])
torch.Size([2, 8])
tensor([[-1.5137, -0.0535,  1.8024,  0.3257,  1.2464,  0.2828, -1.1639, -0.2219],
        [-1.1041, -1.8165,  2.2474, -0.7293, -0.6931, -0.9882,  2.3314,  2.1616]])


## tensor to value

In [29]:
x = torch.randn(1)
print('x:', x)
value = x.item()
print('value:', value)

x: tensor([0.4346])
value: 0.4346344769001007


## tensor to numpy

In [30]:
x = torch.ones(6)
y = x.numpy()
print('x:', x)
print('y:', y)

x: tensor([1., 1., 1., 1., 1., 1.])
y: [1. 1. 1. 1. 1. 1.]


## numpy to tensor

In [32]:
numpyValue = numpy.ones(4)
print('numpyValue:', numpyValue)
tensorVlue = torch.from_numpy(numpyValue)
print('tensorvalue:', tensorVlue)

numpyValue: [1. 1. 1. 1.]
tensorvalue: tensor([1., 1., 1., 1.], dtype=torch.float64)


## 跟踪操作

In [33]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


### 进行张量计算

In [34]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


### 查看计算历史

In [35]:
print(y.grad_fn)

## 再次进行操作

In [36]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>)
tensor(12., grad_fn=<MeanBackward0>)


## 设置跟踪

In [42]:
a = torch.randn(2, 2)
print(a)
a = (a * 3) / (a -1)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor([[0.4520, 0.6989],
        [0.3803, 0.1501]])
tensor([[-2.4745, -6.9636],
        [-1.8414, -0.5299]])
False
True
tensor(58.2867, grad_fn=<SumBackward0>)


## 停止跟踪-I

In [44]:
a.requires_grad_(False)
print(a.requires_grad)

True


## 反向传播

In [51]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
print(y)

while y.data.norm() < 1000:
    y = y * 2
print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(v)

tensor([-0.3851, -0.2733, -0.9332], requires_grad=True)
tensor([-0.7702, -0.5467, -1.8664], grad_fn=<MulBackward0>)
tensor([-394.3221, -279.9095, -955.6151], grad_fn=<MulBackward0>)
tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])


## 停止跟踪-II

In [55]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False
